### PR TITLE
Fix push failed without `rootDir`

### LINKED ISSUE #322: Failed `clasp push` without rootDir
## Expected Behavior

clasp push should be success. Even without `rootDir` in `.clasp.json`.

## Actual Behavior

push failed.

Terminal output is following to:

```
Push failed. Errors:
Project contents must include a manifest file named appsscript.
Files to push were:
└─ appsscript.json
└─ hello.js
```

## Steps to Reproduce the Problem

```sh
clasp create hello
clasp echo 'function hello() {
  Logger.log("Hello, Apps Script!"); 
}' >> hello.js
clasp push
```

## Specifications

  - Node version (`node -v`): v10.5.0
  - Version (`clasp -v`): 1.5.3
  - OS (Mac/Linux/Windows): Mac

### PR DESCRIPTION
**Pull request by fossamagna**
Fixes #322

- [x] `npm run test` succeeds.
- [x] `npm run lint` succeeds.
- [ ] Appropriate changes to README are included in PR.

### CODE REVIEW

File: src/files.ts [hunk 1]
```diff
@@ -104,9 +104,6 @@ export function getProjectFiles(rootDir: string = path.join('.', '/'), callback:
         // Loop through every file.
         const files = filePaths.map((name, i) => {
           // File name
```
Comment (grant) [inline src/files.ts]: `// File name`: This comment no longer applies.
