### PR TITLE
Make running of tests easier

### LINKED ISSUE #197: Tests should be easier to run
## Expected Behavior

You download `clasp`, open up `tests/test.ts` and find and replace `describe.skip` with `describe` (to enable all tests) and then `sudo npm run build && npm run test`. All tests should pass with minimal setup.

## Actual Behavior

As it stands, there's a handful of tests that don't work without extra setup (namely: `clasp push`, `clasp deploy`, `clasp deployments`, `clasp version`)

## Steps to Reproduce the Problem

  1. `git clone https://github.com/google/clasp && cd clasp`
  1. `sudo npm install`
  1.  Un-skip all the tests
  1. `sudo npm run build && npm run test`

## Specifications

  - Node version (`node -v`): 8.9.4
  - Version (`npm list -g | grep clasp`): 1.3.1
  - OS (Mac/Linux/Windows): MacOS

### PR DESCRIPTION
**Pull request by campionfellin**
This can help us make sure all tests actually pass and that we are increasing in code coverage.

Signed-off-by: campionfellin <campionfellin@gmail.com>

Fixes #197

- [x] `npm run test` succeeds.
- [x] `npm run lint` succeeds.
- [ ] Appropriate changes to README are included in PR.

### CODE REVIEW

File: index.ts [hunk 1]
```diff
@@ -387,7 +387,7 @@ commander
                 nonIgnoredFilePaths.map((filePath: string) => {
                   console.error(`└─ ${filePath}`);
                 });
-                process.exit(-1);
+                process.exit(1);
```
Comment (campionfellin) [inline index.ts]: -1 is actually out of range for status codes, and really returns 255. Changed to 1 for consistency.

File: tests/test.ts [hunk 2]
```diff
@@ -94,6 +94,9 @@ describe.skip('Test clasp pull function', () => {
 
 describe.skip('Test clasp push function', () => {
   it('should push local project correctly', () => {
+    fs.removeSync('.claspignore');
+    fs.writeFileSync('Code.js', ' ');
```
Comment (campionfellin) [inline tests/test.ts]: When using `fs.writeFileSync` we need to make sure to at least write a blank space (so `' '` rather than `''` so that the files can be found here. https://github.com/google/clasp/blob/2cd12253a9c77dcd8c021a4949110dc1b9057b41/index.ts#L80

File: tests/test.ts [hunk 3]
```diff
@@ -165,31 +169,12 @@ describe.skip('Test clasp open function', () => {
   });
 });
 
-describe.skip('Test clasp clone function', () => {
```
Comment (campionfellin) [inline tests/test.ts]: This is moved below the `clasp deploy`, `clasp deployments`, and `clasp version` tests because this removes the `.clasp.json` file, which is needed for those tests.

File: tests/test.ts (hunk 2 above)
Comment (grant) [reply tests/test.ts]: Use a constant string instead of a mysterious `' '`. Like:
`const TEST_CODE_JS = 'function test() { Logger.log('test'); }`;
