### PR TITLE
Switch clasp logs from using google-cloud library to googleapis library

### LINKED ISSUE #190: npm install is inconsistent
I'm not able to consistently install clasp. I sometimes get these errors:

```
sudo npm i -g @google/clasp
/usr/local/bin/clasp -> /usr/local/lib/node_modules/@google/clasp/index.js

> grpc@1.12.2 install /usr/local/lib/node_modules/@google/clasp/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Pre-built binaries not installable for grpc@1.12.2 and node@8.11.2 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@google/clasp/node_modules/grpc/src/node'
gyp WARN EACCES user "root" does not have permission to access the dev dir "/var/root/.node-gyp/8.11.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/@google/clasp/node_modules/grpc/.node-gyp"
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/local/lib/node_modules/@google/clasp/node_modules/grpc/.node-gyp/8.11.2"
...
```

# Configs

```
npm -v
5.6.0
node -v
v8.11.2
```

# Command

```
sudo npm i -g @google/clasp
/usr/local/bin/clasp -> /usr/local/lib/node_modules/@google/clasp/index.js
+ @google/clasp@1.3.1
updated 1 package in 11.211s
```

```
sudo npm uninstall -g @google/clasp
```

# Possible Solutions

This seems to not give the errors:
`sudo npm i -g @google/clasp --allow-root`

Another option would be to remove `grpc`, but I believe it is needed with a different npm module.

`sudo npm i -g @google/clasp --unsafe-perm`
seems to always work too.

However, running clasp gives this error still:

```
/usr/local/lib/node_modules/@google/clasp/node_modules/grpc/src/grpc_extension.js:45
    throw error;
    ^

Error: The gRPC binary module was not installed. This may be fixed by running "npm rebuild"
Original error: Cannot find module '/usr/local/lib/node_modules/@google/clasp/node_modules/grpc/src/node/extension_binary/node-v57-darwin-x64-unknown/grpc_node.node'
    at Object.<anonymous> (/usr/local/lib/node_modules/@google/clasp/node_modules/grpc/src/grpc_extension.js:43:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@google/clasp/node_modules/grpc/src/client_interceptors.js:145:12)
    at Module._compile (module.js:652:30)
```

### PR DESCRIPTION
**Pull request by campionfellin**
This gets rid of `@google-cloud/logging` in favor of `googleapis`.

There were not many changes to be made, though the response format is a bit different, so parsing the logs had to be changed. Additionally, new scopes are needed for reading the logs. Finally, `@google-cloud/logging` and `grpc` are removed.

Thanks to @grant for finding a simple solution to the `grpc` problem!
 
Signed-off-by: campionfellin <campionfellin@gmail.com>

Fixes #190 

- [ ] `npm run test` succeeds. (no tests really for `clasp logs`, I manually tested and it seems to work fine.
- [x] `npm run lint` succeeds.
- [ ] Appropriate changes to README are included in PR.

### CODE REVIEW

File: index.ts [hunk 1]
```diff
@@ -740,11 +739,14 @@ commander
...
     }
-    const logger = new logging({
-      projectId,
-    });
-    return logger.getEntries().then(printLogs).catch((err: any) => {
-      console.error(ERROR.LOGS_UNAVAILABLE);
+    getAPICredentials(async () => {
+      const logger = google.logging({version: 'v2', auth: oauth2Client}) as Logging;
+      const { data } = await logger.entries.list({
+        'resourceNames': [
```
Comment (grant) [inline index.ts]: Don't quote object keys.
https://palantir.github.io/tslint/rules/object-literal-key-quotes/

`object-literal-key-quotes: 'as-needed'` can be added to `tslint.json` to prevent this.

File: index.ts [hunk 2]
```diff
@@ -740,11 +739,14 @@ commander
       open(url);
       process.exit(0);
     }
-    const logger = new logging({
-      projectId,
-    });
-    return logger.getEntries().then(printLogs).catch((err: any) => {
-      console.error(ERROR.LOGS_UNAVAILABLE);
+    getAPICredentials(async () => {
+      const logger = google.logging({version: 'v2', auth: oauth2Client}) as Logging;
```
Comment (grant) [inline index.ts]: Put `const logger` here:
https://github.com/google/clasp/blob/master/index.ts#L61

File: index.ts [hunk 3]
```diff
@@ -740,11 +739,14 @@ commander
...
+      const { data } = await logger.entries.list({
+        'resourceNames': [
+          'projects/' + projectId,
```
Comment (grant) [inline index.ts]: Use template literals to build strings with variables:
```js
`projects/${projectId}`,
```

File: index.ts [hunk 4]
```diff
@@ -697,22 +697,21 @@ commander
     open: boolean,
   }) => {
     await checkIfOnline();
-    function printLogs([entries]: any[]) {
+    function printLogs(entries: any[]) {
       for (let i = 0; i < 5; ++i) {
```
Comment (grant) [inline index.ts]: Increase 5 to 50 while you're modifying this method.

File: index.ts (hunk 2 above)
Comment (campionfellin) [reply index.ts]: On a related note, should we do this for `const drive` as well? https://github.com/google/clasp/blob/439772ad83bd061cfe14a7f4d6b5289345aab20f/index.ts#L291

File: index.ts [hunk 5]
```diff
@@ -698,7 +703,7 @@ commander
   }) => {
     await checkIfOnline();
     function printLogs(entries: any[]) {
-      for (let i = 0; i < 5; ++i) {
+      for (let i = 0; i < Math.min(50,entries.length); ++i) {
```
Comment (grant) [inline index.ts]: `50, entries.length`
