### PR TITLE
Fix terminal error when calling clasp logs with invalid projectId and refactor clasp logs

### LINKED ISSUE #518: Terminal error when calling clasp logs with invalid projectId
> Please search [existing issues](https://github.com/google/clasp/issues) before creating a new one.
>
> DON'T DELETE THIS! FILL THESE SECTIONS OUT!

## Expected Behavior

When calling "clasp logs" with an invalid projectId, an error should be thrown, but the terminal should not lock down while perpetually trying to access logs that it can't find.

## Actual Behavior

When executing "clasp logs" with an invalid projectId,  an error code is thrown like the following:
```
(node:8314) UnhandledPromiseRejectionWarning: Error: field [name] has issue [Invalid project resource name]
    at createError (/usr/local/lib/node_modules/@google/clasp/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/@google/clasp/node_modules/axios/lib/core/settle.js:18:12)
    at Unzip.handleStreamEnd (/usr/local/lib/node_modules/@google/clasp/node_modules/axios/lib/adapters/http.js:201:11)
    at Unzip.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:8314) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:8314) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are nothandled will terminate the Node.js process with a non-zero exit code.
```

**but then the terminal continues to be locked on "Grabbing logs..."**

## Steps to Reproduce the Problem

1. Provide an invalid projectId string (for example, with a leading space)
2. execute "clasp logs"

## Specifications

- Node version (`node -v`): v10.15.1
- Version (`clasp -v`): 2.0.1
- OS (Mac/Linux/Windows): Mac

### PR DESCRIPTION
**Pull request by tawAsh1**
Fixes #518, #501

move clasp logs code out to separate file.
project id regexp from here.
https://cloud.google.com/resource-manager/reference/rest/v1beta1/projects

- [x] `npm run test` succeeds.
- [x] `npm run lint` succeeds.
- [x] Appropriate changes to README are included in PR.

### CODE REVIEW

**Comment by tawAsh1** [comment]
I signed it!

File: src/commands.ts [hunk 1]
```diff
@@ -365,34 +365,45 @@ export const logs = async (cmd: { json: boolean; open: boolean; setup: boolean;
...
-        case 401:
-          logError(null, oauthSettings.isLocalCreds ? ERROR.UNAUTHENTICATED_LOCAL : ERROR.UNAUTHENTICATED);
-        case 403:
-          logError(
-            null,
-            oauthSettings.isLocalCreds ? ERROR.PERMISSION_DENIED_LOCAL : ERROR.PERMISSION_DENIED,
-          );
-        default:
-          logError(null, `(${logs.status}) Error: ${logs.statusText}`);
+    if (!projectId.match(/^[a-z][a-z0-9\-]{5,29}$/)) {
```
Comment (grant) [inline src/commands.ts]: Can you move this to a util file as a method?

File: src/commands.ts [hunk 2]
```diff
@@ -365,34 +365,45 @@ export const logs = async (cmd: { json: boolean; open: boolean; setup: boolean;
...
+      });
+      // We have an API response. Now, check the API response status.
+      spinner.stop(true);
+      // Only print filter if provided.
+      if (filter.length) {
+        console.log(filter);
       }
-    } else {
-      printLogs(logs.data.entries);
+      if (logs.status !== 200) {
```
Comment (campionfellin) [inline src/commands.ts]: It could be nice to have this switch statement in a separate method, like

```
parseResponse = (response) => {
    if (response.status != 200) {
   ...
}
```

**Comment by grant** [comment]
Thank you for your contribution @tawAsh1! I've merged the PR.

**Comment by caputchinefrobles** [comment]
Hi. Thanks for the fix. Do you have any idea when the next release with the fix will be available? I'm having such a hard time without `clasp logs`. 

Thank's again.
