### PR TITLE
Fix clasp ignore issues

### LINKED ISSUE #67: .claspignore fails **/node_modules/**
## Expected Behavior

```
**/node_modules/**
**/**
```

Ignores all files in node_modules .

## Actual Behavior

```
 follow-redirects options { protocol: 'https:',
  maxRedirects: 21,
  maxBodyLength: 10485760,
  path: '/v1/projects/SCRUBBED/content',
  method: 'put',
  headers:
   { Accept: 'application/json, text/plain, */*',
     'Content-Type': 'application/json;charset=utf-8',
     Authorization: 'Bearer SCRUBBED',
     'User-Agent': 'google-api-nodejs-client/1.3.1',
     'Content-Length': 3879 },
  agent: undefined,
  auth: undefined,
  hostname: 'script.googleapis.com',
  port: null,
  nativeProtocols:
   { 'http:':
      { _connectionListener: [Function: connectionListener],
        METHODS: [Array],
        STATUS_CODES: [Object],
        Agent: [Object],
        ClientRequest: [Object],
        globalAgent: [Object],
        IncomingMessage: [Object],
        OutgoingMessage: [Object],
        Server: [Object],
        ServerResponse: [Object],
        createServer: [Function: createServer],
        get: [Function: get],
        request: [Function: request] },
     'https:':
      { Server: [Object],
        createServer: [Function: createServer],
        globalAgent: [Object],
        Agent: [Object],
        request: [Function: request],
        get: [Function: get] } } } +0ms
Push failed. Errors:
Invalid value at 'files[2].type' (TYPE_ENUM), "D"
```

`node_modules/fsevents/build/Release/.deps/Release/.node.d` Is getting picked up with the following error.

Added logging to clasp produces:

```
{ name: 'node_modules/fsevents/build/Release/.deps/Release/.node.d' }
{ name: 'node_modules/fsevents/build/Release/.deps/Release/.node',
  type: 'D',
....}
```

from adding:

```
if (getAPIFileType(name) && !anymatch(ignorePatterns, name)) {
                                                nonIgnoredFilePaths.push(name);
                                                var file = {
                                                    name: formattedName,
                                                    type: getAPIFileType(name),
                                                    source: contents[i] //the file contents
                                                };
                                                console.log({name});
                                                console.log(file);
                                                return file;
                                            }
```

Only ignore which did work:

```
node_modules/**
node_modules/fsevents/build/Release/.deps/Release/.node.d
**/**
```

## Specifications

  - Node version (`node -v`) : v8.9.4
  - Version (`npm list | grep clasp`): "@google/clasp@1.1.5"
  - OS (Mac/Linux/Windows): MAC

Maybe you guys should update or drop anymatch?

### PR DESCRIPTION
**Pull request by campionfellin**
This should fix the `getProjectFiles(...)` function.

Additionally, separates out `clasp push` tests, and un-skips one of them, which now passes.

Comments inline explaining the changes.

Signed-off-by: campionfellin <campionfellin@gmail.com>

Fixes #67 possibly... 

- [ ] `npm run test` succeeds.
- [x] `npm run lint` succeeds.
- [ ] Appropriate changes to README are included in PR.

### CODE REVIEW

File: src/files.ts [hunk 1]
```diff
@@ -85,7 +85,8 @@ export async function getProjectFiles(rootDir: string = path.join('.', '/'), cal
       filePaths = filePaths.sort(); // Sort files alphanumerically
       let abortPush = false;
       let nonIgnoredFilePaths: string[] = [];
-      const ignoredFilePaths: string[] = [];
+      let ignoredFilePaths: string[] = [];
+      ignoredFilePaths = ignoredFilePaths.concat(ignorePatterns);
```
Comment (campionfellin) [inline src/files.ts]: `ignoredFilePaths` is returned as the list of files that are ignored (to be printed out for the user). Ideally, we want to show the patterns, not all the files.

File: src/files.ts [hunk 2]
```diff
@@ -112,16 +113,17 @@ export async function getProjectFiles(rootDir: string = path.join('.', '/'), cal
 
         // check ignore files
         const ignoreMatches = multimatch(filePaths, ignorePatterns, { dot: true });
+        const intersection: string[] = filePaths.filter(file => !ignoreMatches.includes(file));
 
-        // Loop through every file.
-        const files = filePaths
+        // Loop through files that are not ignored
```
Comment (campionfellin) [inline src/files.ts]: Looping through every file (and doing all this logic to each file, takes forever). Just loop through non-ignored files to make sure they are valid.

File: src/files.ts [hunk 3]
```diff
@@ -112,16 +113,17 @@ export async function getProjectFiles(rootDir: string = path.join('.', '/'), cal
 
         // check ignore files
         const ignoreMatches = multimatch(filePaths, ignorePatterns, { dot: true });
+        const intersection: string[] = filePaths.filter(file => !ignoreMatches.includes(file));
```
Comment (campionfellin) [inline src/files.ts]: This gets the files that are not ignored. Before this, we were not really using `multimatch` that effectively.

File: src/files.ts [hunk 4]
```diff
@@ -112,16 +113,17 @@ export async function getProjectFiles(rootDir: string = path.join('.', '/'), cal
...
+        // Loop through files that are not ignored
+        const files = intersection
           .map((name, i) => {
             const normalizedName = path.normalize(name);
 
             let type = getAPIFileType(name);
 
             // File source
-            let source = contents[i];
+            let source = fs.readFileSync(name).toString();
```
Comment (campionfellin) [inline src/files.ts]: Since we are not looping through every file, they are no longer in order. Just read the file based on name.

**Comment by campionfellin** [comment]
screen shot 2019-02-19 at 9 00 04 pm

File: tests/test.ts [hunk 5]
```diff
@@ -282,7 +249,7 @@ describe('Test clasp status function', () => {
     const result = spawnSync(CLASP, ['status', '--json'], { encoding: 'utf8', cwd: tmpdir });
     expect(result.status).to.equal(0);
     const resultJson = JSON.parse(result.stdout);
-    expect(resultJson.untrackedFiles).to.have.members(['dist/shouldBeIgnored', 'dist/should/alsoBeIgnored']);
+    expect(resultJson.untrackedFiles).to.have.members(['**/**', '!dist/build/main.js', '!dist/appsscript.json']);
```
Comment (campionfellin) [inline tests/test.ts]: This test was failing. It now shows untracked files as the globs you put in `.claspignore`, not the files that it found and is not tracking. (this would be a pain if it printed out every file under `node_modules`)

File: src/files.ts (hunk 3 above)
Comment (grant) [reply src/files.ts]: Put these GitHub comments in the source code (where appropriate).

File: tests/commands/push.ts [hunk 6]
```diff
@@ -0,0 +1,40 @@
...
+import {
+  cleanup,
+  setup,
+} from '../functions';
+
+describe('Test clasp push function', () => {
+  before(setup);
+  it('should push local project correctly', () => {
+    fs.writeFileSync('Code.js', TEST_CODE_JS);
+    fs.writeFileSync('.claspignore', '**/**\n!Code.js\n!appsscript.json');
```
Comment (grant) [inline tests/commands/push.ts]: Write maintainable tests:

['**/**', '!Code.js', 'appsscript.json'].join('\n')

File: tests/commands/push.ts [hunk 7]
```diff
@@ -0,0 +1,40 @@
...
+    const result = spawnSync(
+      CLASP, ['push'], { encoding: 'utf8', input: 'y' },
+    );
+    expect(result.stdout).to.contain('Pushed');
+    expect(result.stdout).to.contain('files.');
+    expect(result.status).to.equal(0);
+  });
+  it.skip('should return non-0 exit code when push failed', () => {
+    fs.writeFileSync('.claspignore', '**/**\n!Code.js\n!appsscript.json\n!unexpected_file');
```
Comment (grant) [inline tests/commands/push.ts]: ditto

**Comment by campionfellin** [comment]
I think pulling out `clasp status` tests should be a separate PR, to keep this one small.

An additional PR can be to unskip all the tests and make sure they work.
An additional PR can be to change all
```
  before(function () {
    if (IS_PR) {
      this.skip();
    }
    setup();
  });
```
to `before(setup);` as I have been doing with each re-factor.

**Comment by grant** [comment]
> I think pulling out `clasp status` tests should be a separate PR, to keep this one small.

Acknowledged.

File: src/files.ts (hunk 1 above)
Comment (grant) [reply src/files.ts]:
```ts
let ignoredFilePaths: string[] = [];
ignoredFilePaths = ignoredFilePaths.concat(ignorePatterns);
```

===

```ts
let ignoredFilePaths: string[] = [...ignorePatterns];
```
