### PR TITLE
Modify tests to avoid spawnSync behavior on Windows

### LINKED ISSUE #231: Tests fail on Windows
## Expected Behavior
After cloning master and installing on Windows, tests should pass.

## Actual Behavior
Tests fail with the error "AssertionError: expected null to equal 0". Logging the 'result' object reveals that spawnSync is throwing an ENOENT error. Apparently, spawnSync on Windows requires that some commands have the '.cmd' suffix in order to run successfully. I'm opening a pull request to fix this.

## Steps to Reproduce the Problem

  1. Run tests on Windows
  1. Tests fail.
  1. Change 'clasp' to 'clasp.cmd' throughout test.ts
  1. Tests pass.

## Specifications

  - Node version 10.4.1
  - Version 1.4.0
  - Windows 10

### PR DESCRIPTION
**Pull request by wilt00**
Fixes #231

- [X] `npm run test` succeeds. (!)
- [X] `npm run lint` succeeds.
- [X] Appropriate changes to README are included in PR. (N/A)

### CODE REVIEW

File: tests/test.ts [hunk 1]
```diff
@@ -9,18 +9,19 @@ import { getAPIFileType, getScriptURL, saveProjectId } from './../src/utils.js';
 const { spawnSync } = require('child_process');
 const TEST_CODE_JS = 'function test() { Logger.log(\'test\'); }';
 const TEST_JSON = '{"timeZone": "America/New_York"}';
+const CLASP = (os.type() === 'Windows_NT') ? 'clasp.cmd' : 'clasp';
```
Comment (grant) [inline tests/test.ts]: A comment would be nice here.
But this is pretty self-explanatory too.

**Comment by wilt00** [comment]
Yep, the tests pass! The only bit of weirdness left is that `npm run build` doesn't work because the semicolon gets ignored and both commands get combined together. I was able to build by running `npx tsc --project tsconfig.json` and `npm i -g --loglevel=error` as separate commands, then running `npm run test`. Double ampersand seems to work fine.

Complete error message in case someone needs to search for it:
```
error TS5023: Unknown compiler option '-g'.
error TS5023: Unknown compiler option '--loglevel=error;'.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @google/clasp@1.4.0 build: `tsc --project tsconfig.json; npm i -g --loglevel=error;`
npm ERR! Exit status 1
```

**Comment by grant** [comment]
If `&&` fixes it (instead of `;`), let's change it. PRs are welcome!
