### PR TITLE
Confirm overwrite using inquirer when manifest conflict occurs

### LINKED ISSUE #424: clasp push warns if you have a different manifest locally
## Expected Behavior

I want command line option of `clasp pull` that pulls `appsscript.json` only.

example : `clasp pull --setting-only`

Using this command after setting 

## Actual Behavior

There is a problem with the management method of `appsscript.json`.

If you run `clasp push` after setting something in the web GUI, the local `appsscript.json` is outdated.
Pushing old `appsscript.json` will unexpectedly change setting by web GUI .

## Steps to Reproduce the Problem

Example

  1. `clasp create`
  1. create `Code.js` in local
  1. `clasp push`
  1. Configure to publish to web by web GUI .
  1. `clasp push`

Web publishing is disabled.

## Specifications

  - Node version (`node -v`):  v11.2.0
  - Version (`clasp -v`): 4927ee4 
  - OS (Mac/Linux/Windows): Mac

What do you think about this proposal?

### PR DESCRIPTION
**Pull request by takanakahiko**
Fixes #424 

This PR is according to https://github.com/google/clasp/issues/424#issuecomment-442899333

`clasp push` or `clasp push --watch`
-> If manifest conflict occurs, confirm overwrite using `inquirer`

`clasp push --force` or `clasp push --watch --force`
-> If manifest conflict occurs,  force pushing

- [x] `npm run test` succeeds.
- [x] `npm run lint` succeeds.
- [x] Appropriate changes to README are included in PR.

### CODE REVIEW

File: src/manifest.ts [hunk 1]
```diff
@@ -87,6 +97,40 @@ export async function enableOrDisableAdvanceServiceInManifest(serviceId: string,
   await writeManifest(manifest);
 }
 
+/**
+ * Reads the remote appsscript.json manifest file.
+ * @returns {Promise} A promise to get the remote manifest file as object.
+ * @see https://developers.google.com/apps-script/concepts/manifests
+ */
+export async function readRemoteManifest() : Promise<Manifest>  {
+  await checkIfOnline();
```
Comment (grant) [inline src/manifest.ts]: Can you reuse more of the `clasp pull` method?

Refactor `clasp pull` so we use a common method.
We shouldn't see `await script.projects.getContent({scriptId});`.

```ts
const content = await getProjectContent(scriptId);
const files = content.data.files || [];
const manifest = files.find((file) => file.name === PROJECT_MANIFEST_BASENAME);
```

Also, Apps Script forces manifests to be valid JSON so we don't need to try JSON parse.

File: src/files.ts [hunk 2]
```diff
@@ -249,49 +251,47 @@ export async function fetchProject(scriptId: string, rootDir = '', versionNumber
...
-    } else if (projectFiles) {
-      const [nonIgnoredFilePaths] = projectFiles;
-      const filesForAPI: any = files;
-      script.projects.updateContent(
-        {
+      return logError(err, LOG.PUSH_FAILURE);
+    }
+    const [nonIgnoredFilePaths] = projectFiles || [[]];
+    const filesForAPI: any = files;
+    script.projects.updateContent(
```
Comment (grant) [inline src/files.ts]: Note: It would be nice to convert this to `await script.projects.updateContent`, but it's not required for this PR.

File: src/commands.ts [hunk 3]
```diff
@@ -87,12 +105,20 @@ export const push = async (cmd: { watch: boolean }) => {
           return;
         }
       }
+      if( !cmd.force && await manifestHasChanges() && !await confirmManifestUpdate() ){
```
Comment (grant) [inline src/commands.ts]: Can you check the formatting? `if (!cmd...`

**Comment by takanakahiko** [comment]
I'm sorry, I am busy so I will work for this PR tomorrow.

File: src/commands.ts (hunk 3 above)
Comment (takanakahiko) [reply src/commands.ts]: There was no error with lint.
What does the coding rule based on?

**Comment by takanakahiko** [comment]
Coding work is finished!
Please review!

**Comment by takanakahiko** [comment]
Coding work is finished!
Please review!

**Comment by takanakahiko** [comment]
Coding work is finished!
Please review!

**Comment by grant** [comment]
Thanks for the PR!
