### PR TITLE
Issue 660

### LINKED ISSUE #660: Clasp not pushing html files
> Please search [existing issues](https://github.com/google/clasp/issues) before creating a new one.
>
> DON'T DELETE THIS! FILL THESE SECTIONS OUT!

## Expected Behavior
Should push both html and js files

## Actual Behavior
Only pushing .js files to app scipt project

## Steps to Reproduce the Problem
I have no idea how this issue came up, it was working fine and suddenly it starts pushing js files only.

## Specifications

- Node version (`node -v`): 10.15.0
- Version (`clasp -v`): 2.2.0
- OS (Mac/Linux/Windows): Windows 7

### PR DESCRIPTION
**Pull request by PopGoesTheWza**
Fixes #660

- [x] `npm run test` succeeds.
- [x] `npm run lint` succeeds.
- [x] Appropriate changes to README are included in PR.

### CODE REVIEW

File: src/dotfile.ts [hunk 1]
```diff
@@ -106,7 +106,7 @@ export const DOTFILE = {
         const buffer = stripBom(fs.readFileSync(DOT.IGNORE.PATH, FS_OPTIONS));
         resolve(splitLines(buffer).filter((name: string) => name));
       } else {
-        resolve(['**/**', '!appsscript.json', '!*.js', '!*.ts']);
+        resolve(['**/**', '!appsscript.json', '!*.js', '!*.ts', '!*.html']);
```
Comment (grant) [inline src/dotfile.ts]: We have an object of all valid file extensions. This includes .gs

Can we use that object with constants instead of this?

File: README.md [hunk 2]
```diff
@@ -459,6 +459,7 @@ If no `.claspignore` is specified, a default set of patterns is applied. The def
 !appsscript.json
 !*.js
 !*.ts
+!*.html
```
Comment (grant) [inline README.md]: Also gs files

File: tests/commands/push.ts [hunk 3]
```diff
@@ -1,11 +1,11 @@
...
-
+import { spawnSync } from 'child_process';
 import { expect } from 'chai';
 import fs from 'fs-extra';
-import { spawnSync } from 'child_process';
+import { describe, it } from 'mocha';
+import { CLASP, TEST_CODE_JS } from '../constants';
+import { cleanup, setup } from '../functions';
 
+// TODO: add some `.html` files to tests
```
Comment (grant) [inline tests/commands/push.ts]: Can we add a test so we don’t break anything in the future? I can’t publish this till next week.

File: src/dotfile.ts (hunk 1 above)
Comment (PopGoesTheWza) [reply src/dotfile.ts]: @grant Sorry but I cannot locate such object

**Comment by PopGoesTheWza** [comment]
> Note: I can’t publish until Monday at the earliest.

I'm confident no one will die meanwhile...

**Comment by grant** [comment]
Thanks.
