### PR TITLE
Package dependencies update and linting/typing improvement

### LINKED ISSUE #603: (Minor) deprecated `opn` packages should be replace with its successor `open`
## Steps to Reproduce the Problem

1. check clasp's packages.json for `opn` depenecy
1. check [`opn` npm page](https://www.npmjs.com/package/opn) for deprecation warning
1. check [`open` npm page](https://www.npmjs.com/package/open) to verify same author/same api

## Specifications

- Node version (`node -v`): n.a.
- Version (`clasp -v`): @latest
- OS (Mac/Linux/Windows): n.a.

### PR DESCRIPTION
**Pull request by PopGoesTheWza**
Fixes #603 #604 

- [x] `npm run test` succeeds.
- [x] `npm run lint` succeeds.
- [ ] Appropriate changes to README are included in PR.

### CODE REVIEW

**Comment by PopGoesTheWza** [comment]
updating `nyc` package, partly addressing #607

**Comment by PopGoesTheWza** [comment]
@grant can someone review this PR please?

File: src/utils.ts [hunk 1]
```diff
@@ -400,7 +399,7 @@ function getScriptTypeName(type: string) {
  * Handles error of each command.
  */
 // tslint:disable-next-line:no-any
-export function handleError(command: (...args: any[]) => Promise<void>) {
+export function handleError(command: (...args: any[]) => Promise<any>) {
```
Comment (grant) [inline src/utils.ts]: `void` is better than `any`. I think this returns `void` and should be kept this way.

**Comment by grant** [comment]
Thanks for waiting after Google I/O last week.
Please use *branches* rather than `PopGoesTheWza:master` for future PRs to prevent so many commits.

Will merge after you address the comment.

File: src/utils.ts (hunk 1 above)
Comment (PopGoesTheWza) [reply src/utils.ts]: @grant There are three instances of `handleError` usage which fails when `Promise<void>` is expected.

```ts
  .action(handleError(openCmd));
```

```ts
  .action(handleError(logs));
```

```ts
  .action(handleError(apis));
```

Those three functions return `Promise<ChildProcess | undefined>`

To fix those linting errors, we can either redefine `handleError` to accept either `(...args: any[]) => Promise<any>` or `(...args: any[]) => Promise<unknown>`

Else `openCmd`, 'logs' and `apis` require to be adjusted somehow. Since I am not familiar with these parts of Clasp, I did not invest too much in the latest option.

Please advise.

**Comment by PopGoesTheWza** [comment]
> Please use _branches_ rather than `PopGoesTheWza:master` for future PRs to prevent so many commits.

I will look into how branches work and proceed so in the future.

File: README.md [hunk 2]
```diff
@@ -509,7 +515,7 @@ This requires using the environment variables `HTTP_PROXY` / `HTTPS_PROXY`.
 
 Using clasp for your project? Add a README badge to show it off: [![clasp](https://img.shields.io/badge/built%20with-clasp-4285f4.svg)](https://github.com/google/clasp)
 
-```
+```text
```
Comment (grant) [inline README.md]: \`\`\`md

File: src/commands/openCmd.ts [hunk 3]
```diff
@@ -87,13 +87,18 @@ export default async (scriptId: string, cmd: {
...
-  }]) as {deploymentId: string};
+  }]);
   const deployment = await script.projects.deployments.get({deploymentId: answers.deploymentId});
   console.log(LOG.OPEN_WEBAPP(answers.deploymentId));
-  open(getWebApplicationURL(deployment.data), { wait: false });
+  const target = getWebApplicationURL(deployment.data);
+  if (target) {
+    open(target, { wait: false });
+  } else {
+    // TODO: handle undefined
```
Comment (grant) [inline src/commands/openCmd.ts]: Return something:
```ts
return logError(null, `Could not open deployment: ${deployment}`);
```

File: src/files.ts [hunk 4]
```diff
@@ -9,8 +9,10 @@ import { DOT, DOTFILE } from './dotfile';
 import { ERROR, LOG, checkIfOnline, getAPIFileType, getProjectSettings, logError, spinner } from './utils';
 
 const ts2gas = require('ts2gas');
+// TODO: include ts2gas .d.ts in package
```
Comment (grant) [inline src/files.ts]: Can we do this now? What needs to change?

Comment (PopGoesTheWza) [reply src/files.ts]: @grant currently grant/ts2gas has:

[x] tsconfig.json with `declaration` set to `true`
[x] package.json with `types` set to `./src/index.d.ts`
[ ] `.d.ts` (and optionaly `.ts` included in the published package

Last point is because of `.npmignore` which excludes any `*.ts`

If you want, I could issue a new PR (from a `branch`) with the `.npmignore` change, and possibly the additionnal changes:

- `src` folder contains only the source `.ts`
- a new `lib` folder which will contains `.js` and `.d.ts``
- `package.json` attributes `main` and `types` to properly point to the `lib` folder

Comment (grant) [reply src/files.ts]: See https://github.com/grant/ts2gas/issues/39

Let's fix it and publish the `.d.ts`.

Comment (PopGoesTheWza) [reply src/files.ts]: This could wait for a future PR IMHO. For an effective change, we need a new `ts2gas` release with updated dependency in `package.json`

**Comment by grant** [comment]
Can't merge. Conflict.

**Comment by PopGoesTheWza** [comment]
@grant I see the cause of the conflict and will push something to (tentatively) fix it

**Comment by PopGoesTheWza** [comment]
@grant Once completed, I'll issue a new PR to fix the last linting error (which was in conflict)

> Consider using "forEach" instead of "map" as its return value is not being used here. (typescript:S2201)

**Comment by grant** [comment]
Merged.
